name: Build & Test

on:
  push:
    branches:
      - main

  release:
    types: [published]

  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout mqoi
        uses: actions/checkout@v2
    
      - name: Checkout qoi
        uses: actions/checkout@v2
        with:
          repository: phoboslab/qoi
          path: qoi

      - name: Install GNU Octave
        run: |
          sudo apt-get install octave liboctave-dev
          octave --version

      - name: Download test images
        run: |
          wget https://qoiformat.org/qoi_test_images.zip
          unzip qoi_test_images.zip
          rm qoi_test_images.zip

      - name: Install mqoi
        run: |
          octave --no-gui --no-window-system --silent --eval "addpath (pwd); savepath ();"

      - name: Run tests (M)
        run: |
          octave --no-gui --no-window-system --silent --eval "test_qoiread qoi_test_images"

      - name: Compile mqoi
        run: |
          mkoctfile -mex qoiread.c -Iqoi

      - name: Run tests (MEX)
        run: |
          octave --no-gui --no-window-system --silent --eval "test_qoiread qoi_test_images"
